class Descriptor:
    @property
    def name(self) -> str: ...
    @property
    def is_linked(self) -> bool: ...
    def field_names(self) -> list[str]: ...
    def ref_fields(self) -> list[tuple[int, str]]: ...
    def oneofs(self) -> list[tuple[str, list[str]]]: ...
    def link(
        self,
        mapping: dict[int, type],
        fast_init: tuple[type, list[object]] | None = None,
    ) -> None: ...
    def encode(self, instance: object) -> bytes: ...
    def decode[T](self, cls: type[T], data: bytes) -> T: ...

def compile_descriptor(data: bytes) -> Descriptor: ...
