"""Structural well-known types, bundled with fastproto.

@generated by scripts/regen.py from protoc's google/protobuf descriptors --
DO NOT EDIT. `Timestamp` and `Duration` are not here: the codec maps them to
`datetime` / `timedelta` natively. Note that `Any` is protobuf's
``google.protobuf.Any`` message, not ``typing.Any``.
"""

# pyright: reportUnknownVariableType=false
from dataclasses import dataclass, field
from enum import IntEnum

from fastproto import Message, Scalar, message


_ANY_DESCRIPTOR = bytes.fromhex(  # @generated
    "0a03416e7912190a08747970655f75726c18012001280952077479706555726c12140a0576616c756518022001280c520576616c7565"
)


@message(_ANY_DESCRIPTOR)
@dataclass(slots=True)
class Any(Message):
    type_url: Scalar.String = ""
    value: Scalar.Bytes = b""


_EMPTY_DESCRIPTOR = bytes.fromhex(  # @generated
    "0a05456d707479"
)


@message(_EMPTY_DESCRIPTOR)
@dataclass(slots=True)
class Empty(Message):
    pass


_FIELDMASK_DESCRIPTOR = bytes.fromhex(  # @generated
    "0a094669656c644d61736b12140a05706174687318012003280952057061746873"
)


@message(_FIELDMASK_DESCRIPTOR)
@dataclass(slots=True)
class FieldMask(Message):
    paths: list[Scalar.String] = field(default_factory=list)


class NullValue(IntEnum):
    NULL_VALUE = 0


_STRUCT_DESCRIPTOR = bytes.fromhex(  # @generated
    "0a06537472756374123b0a066669656c647318012003280b32232e676f6f676c652e70726f746f6275662e5374727563742e4669656c6473456e74727952066669656c64731a510a0b4669656c6473456e74727912100a036b657918012001280952036b6579122c0a0576616c756518022001280b32162e676f6f676c652e70726f746f6275662e56616c7565520576616c75653a023801"
)


@message(_STRUCT_DESCRIPTOR)
@dataclass(slots=True)
class Struct(Message):
    fields: "dict[Scalar.String, Value]" = field(default_factory=dict)


_VALUE_DESCRIPTOR = bytes.fromhex(  # @generated
    "0a0556616c7565123b0a0a6e756c6c5f76616c756518012001280e321a2e676f6f676c652e70726f746f6275662e4e756c6c56616c7565480052096e756c6c56616c756512230a0c6e756d6265725f76616c75651802200128014800520b6e756d62657256616c756512230a0c737472696e675f76616c75651803200128094800520b737472696e6756616c7565121f0a0a626f6f6c5f76616c756518042001280848005209626f6f6c56616c7565123c0a0c7374727563745f76616c756518052001280b32172e676f6f676c652e70726f746f6275662e5374727563744800520b73747275637456616c7565123b0a0a6c6973745f76616c756518062001280b321a2e676f6f676c652e70726f746f6275662e4c69737456616c7565480052096c69737456616c756542060a046b696e64"
)


@message(_VALUE_DESCRIPTOR)
@dataclass(slots=True)
class Value(Message):
    null_value: NullValue | None = None
    number_value: Scalar.Double | None = None
    string_value: Scalar.String | None = None
    bool_value: Scalar.Bool | None = None
    struct_value: "Struct | None" = None
    list_value: "ListValue | None" = None


_LISTVALUE_DESCRIPTOR = bytes.fromhex(  # @generated
    "0a094c69737456616c7565122e0a0676616c75657318012003280b32162e676f6f676c652e70726f746f6275662e56616c7565520676616c756573"
)


@message(_LISTVALUE_DESCRIPTOR)
@dataclass(slots=True)
class ListValue(Message):
    values: "list[Value]" = field(default_factory=list)


_DOUBLEVALUE_DESCRIPTOR = bytes.fromhex(  # @generated
    "0a0b446f75626c6556616c756512140a0576616c7565180120012801520576616c7565"
)


@message(_DOUBLEVALUE_DESCRIPTOR)
@dataclass(slots=True)
class DoubleValue(Message):
    value: Scalar.Double = 0.0


_FLOATVALUE_DESCRIPTOR = bytes.fromhex(  # @generated
    "0a0a466c6f617456616c756512140a0576616c7565180120012802520576616c7565"
)


@message(_FLOATVALUE_DESCRIPTOR)
@dataclass(slots=True)
class FloatValue(Message):
    value: Scalar.Float = 0.0


_INT64VALUE_DESCRIPTOR = bytes.fromhex(  # @generated
    "0a0a496e74363456616c756512140a0576616c7565180120012803520576616c7565"
)


@message(_INT64VALUE_DESCRIPTOR)
@dataclass(slots=True)
class Int64Value(Message):
    value: Scalar.Int64 = 0


_UINT64VALUE_DESCRIPTOR = bytes.fromhex(  # @generated
    "0a0b55496e74363456616c756512140a0576616c7565180120012804520576616c7565"
)


@message(_UINT64VALUE_DESCRIPTOR)
@dataclass(slots=True)
class UInt64Value(Message):
    value: Scalar.UInt64 = 0


_INT32VALUE_DESCRIPTOR = bytes.fromhex(  # @generated
    "0a0a496e74333256616c756512140a0576616c7565180120012805520576616c7565"
)


@message(_INT32VALUE_DESCRIPTOR)
@dataclass(slots=True)
class Int32Value(Message):
    value: Scalar.Int32 = 0


_UINT32VALUE_DESCRIPTOR = bytes.fromhex(  # @generated
    "0a0b55496e74333256616c756512140a0576616c756518012001280d520576616c7565"
)


@message(_UINT32VALUE_DESCRIPTOR)
@dataclass(slots=True)
class UInt32Value(Message):
    value: Scalar.UInt32 = 0


_BOOLVALUE_DESCRIPTOR = bytes.fromhex(  # @generated
    "0a09426f6f6c56616c756512140a0576616c7565180120012808520576616c7565"
)


@message(_BOOLVALUE_DESCRIPTOR)
@dataclass(slots=True)
class BoolValue(Message):
    value: Scalar.Bool = False


_STRINGVALUE_DESCRIPTOR = bytes.fromhex(  # @generated
    "0a0b537472696e6756616c756512140a0576616c7565180120012809520576616c7565"
)


@message(_STRINGVALUE_DESCRIPTOR)
@dataclass(slots=True)
class StringValue(Message):
    value: Scalar.String = ""


_BYTESVALUE_DESCRIPTOR = bytes.fromhex(  # @generated
    "0a0a427974657356616c756512140a0576616c756518012001280c520576616c7565"
)


@message(_BYTESVALUE_DESCRIPTOR)
@dataclass(slots=True)
class BytesValue(Message):
    value: Scalar.Bytes = b""
