"""``protoc-gen-fastproto``: the protoc code generator plugin.

protoc runs this as a subprocess, handing it a serialized ``CodeGeneratorRequest``
on stdin and reading a ``CodeGeneratorResponse`` from stdout. For every input
``.proto`` we emit a ``<name>_pb.py`` containing readable dataclasses annotated
with ``Scalar.*`` and decorated with :func:`fastproto.message`.

The embedded descriptor for each message is simply that message's own
``DescriptorProto`` bytes -- exactly what the native ``compile_descriptor``
consumes at import time.

This package is split by responsibility: :mod:`._index` (descriptor reflection
and naming), :mod:`._render` (source generation), and :mod:`._validate` (schema
name checks). The public entry points -- :func:`generate`,
:func:`generate_wellknown`, and :func:`main` -- live here.

Note: ``google.protobuf`` is used *here*, at build time, only to parse the
request. Generated modules depend solely on ``fastproto`` at runtime.
"""

import sys
from typing import TYPE_CHECKING

from google.protobuf.compiler import plugin_pb2

from ._index import TypeIndex
from ._render import ModuleRenderer, ShortNameCollisionError
from ._validate import InvalidSchemaError, SchemaValidator

if TYPE_CHECKING:
    from collections.abc import Iterable

    from google.protobuf.descriptor_pb2 import FileDescriptorProto

# Files whose types are bundled as structural dataclasses in
# ``fastproto.wellknown`` (Timestamp/Duration are native and excluded).
WELLKNOWN_PROTOS = [
    "google/protobuf/any.proto",
    "google/protobuf/empty.proto",
    "google/protobuf/field_mask.proto",
    "google/protobuf/struct.proto",
    "google/protobuf/wrappers.proto",
]

_WELLKNOWN_HEADER = '''"""Structural well-known types, bundled with fastproto.

@generated by scripts/regen.py from protoc's google/protobuf descriptors --
DO NOT EDIT. `Timestamp` and `Duration` are not here: the codec maps them to
`datetime` / `timedelta` natively. Note that `Any` is protobuf's
``google.protobuf.Any`` message, not ``typing.Any``.
"""

# pyright: reportUnknownVariableType=false
from dataclasses import dataclass, field
from enum import IntEnum

from fastproto import Message, Scalar, message'''


def generate(
    request: plugin_pb2.CodeGeneratorRequest,
) -> plugin_pb2.CodeGeneratorResponse:
    """Turn a protoc request into a response of generated ``_pb.py`` files."""
    response = plugin_pb2.CodeGeneratorResponse()
    response.supported_features = (
        plugin_pb2.CodeGeneratorResponse.FEATURE_PROTO3_OPTIONAL
    )
    files_by_name = {f.name: f for f in request.proto_file}
    index = TypeIndex(request.proto_file)
    for proto_name in request.file_to_generate:
        file = files_by_name[proto_name]
        try:
            SchemaValidator(file).validate()
            content = ModuleRenderer(file, index).render()
        except (ShortNameCollisionError, InvalidSchemaError) as exc:
            response.error = str(exc)
            return response
        output = response.file.add()
        output.name = _output_name(proto_name)
        output.content = content
    return response


def generate_wellknown(files: "Iterable[FileDescriptorProto]") -> str:
    """Render ``fastproto/wellknown.py`` from the WKT file descriptors.

    The well-known ``.proto`` files don't import each other, so their blocks
    concatenate safely into one module. Shared by ``scripts/regen.py`` and the
    golden test.
    """
    by_name = {f.name: f for f in files}
    ordered = [by_name[name] for name in WELLKNOWN_PROTOS]
    index = TypeIndex(ordered)
    blocks = [_WELLKNOWN_HEADER]
    for file in ordered:
        blocks += ModuleRenderer(file, index).blocks()
    return "\n\n\n".join(blocks) + "\n"


def main() -> None:
    """Read a request from stdin and write the response to stdout."""
    request = plugin_pb2.CodeGeneratorRequest.FromString(sys.stdin.buffer.read())
    sys.stdout.buffer.write(generate(request).SerializeToString())


def _output_name(proto_name: str) -> str:
    """Map ``foo/bar.proto`` to ``foo/bar_pb.py``."""
    return f"{proto_name.removesuffix('.proto')}_pb.py"


if __name__ == "__main__":
    main()
