"""Source generation: turn one ``FileDescriptorProto`` into a ``_pb.py`` module.

``ModuleRenderer`` holds the file and the shared :class:`TypeIndex` and emits the
readable dataclass module — header, enums, and the decorated message classes.
"""

from google.protobuf.descriptor_pb2 import (
    DescriptorProto,
    EnumDescriptorProto,
    FieldDescriptorProto,
    FileDescriptorProto,
)

from ._index import NATIVE_WKT, TypeIndex, all_messages, has_presence, is_named_type

# Field numbers of the synthetic map entry message (key, value).
_MAP_KEY_FIELD = 1
_MAP_VALUE_FIELD = 2

# proto scalar type -> (Scalar alias, default literal)
SCALAR: dict[int, tuple[str, str]] = {
    FieldDescriptorProto.TYPE_DOUBLE: ("Scalar.Double", "0.0"),
    FieldDescriptorProto.TYPE_FLOAT: ("Scalar.Float", "0.0"),
    FieldDescriptorProto.TYPE_INT64: ("Scalar.Int64", "0"),
    FieldDescriptorProto.TYPE_UINT64: ("Scalar.UInt64", "0"),
    FieldDescriptorProto.TYPE_INT32: ("Scalar.Int32", "0"),
    FieldDescriptorProto.TYPE_FIXED64: ("Scalar.Fixed64", "0"),
    FieldDescriptorProto.TYPE_FIXED32: ("Scalar.Fixed32", "0"),
    FieldDescriptorProto.TYPE_BOOL: ("Scalar.Bool", "False"),
    FieldDescriptorProto.TYPE_STRING: ("Scalar.String", '""'),
    FieldDescriptorProto.TYPE_BYTES: ("Scalar.Bytes", 'b""'),
    FieldDescriptorProto.TYPE_UINT32: ("Scalar.UInt32", "0"),
    FieldDescriptorProto.TYPE_SFIXED32: ("Scalar.SFixed32", "0"),
    FieldDescriptorProto.TYPE_SFIXED64: ("Scalar.SFixed64", "0"),
    FieldDescriptorProto.TYPE_SINT32: ("Scalar.SInt32", "0"),
    FieldDescriptorProto.TYPE_SINT64: ("Scalar.SInt64", "0"),
}


class ShortNameCollisionError(Exception):
    """Two types visible from one module share a short class name."""


class ModuleRenderer:
    """Renders the ``<name>_pb.py`` source for one proto file."""

    def __init__(self, file: FileDescriptorProto, index: TypeIndex) -> None:
        self._file = file
        self._index = index

    def render(self) -> str:
        """Render the full module source: header plus enum/message blocks."""
        return "\n\n\n".join([self._header(), *self._file_blocks()]) + "\n"

    def blocks(self) -> list[str]:
        """Render only the enum/message blocks (no header) — used for the WKT bundle."""
        return self._file_blocks()

    def _header(self) -> str:
        """Render the module header: banner, imports, and cross-file imports."""
        file = self._file
        natives = self._native_names()
        external = self._external_imports()
        # `field(...)` is emitted for repeated/map fields (default_factory) and
        # for nested-enum singular fields (a deferred zero-value factory).
        needs_field = any(
            f.label == FieldDescriptorProto.LABEL_REPEATED
            or (
                f.type == FieldDescriptorProto.TYPE_ENUM
                and "." in self._index.qualified(f)
            )
            for msg in all_messages(file)
            for f in msg.field
        )
        has_enum = bool(file.enum_type) or any(m.enum_type for m in all_messages(file))
        dataclass_import = (
            "from dataclasses import dataclass, field"
            if needs_field
            else "from dataclasses import dataclass"
        )
        lines = [
            "# @generated by fastproto. DO NOT EDIT.",
            f"# source: {file.name}",
        ]
        if needs_field:
            # `field(default_factory=list/dict)` makes Pyright's strict mode
            # infer `list[Unknown]`; the annotation already states the type.
            lines.append("# pyright: reportUnknownVariableType=false")
        lines.append(dataclass_import)
        if natives:
            lines.append(f"from datetime import {', '.join(natives)}")
        if has_enum:
            lines.append("from enum import IntEnum")
        names = (
            "Message, Scalar, message" if self._uses_scalar() else "Message, message"
        )
        lines += ["", f"from fastproto import {names}"]
        if external:
            lines += ["", *external]
        return "\n".join(lines)

    def _external_imports(self) -> list[str]:
        """Dual-import lines for types this file references from other files.

        Emits ``try: from .x_pb import Y / except ImportError: from x_pb import Y``
        so generated modules work both inside a package and in a flat directory.
        Only the top-level container is imported; nested types are reached through
        it (``Outer.Inner``). Raises :class:`ShortNameCollisionError` when two
        distinct top-level types share a name (the imports couldn't distinguish).
        """
        file = self._file
        # top-level name -> the `file:name` that owns it, seeded with this file's
        # own top-level definitions.
        owner: dict[str, str] = {}
        for enum in file.enum_type:
            owner[enum.name] = f"{file.name}:{enum.name}"
        for msg in file.message_type:
            owner[msg.name] = f"{file.name}:{msg.name}"

        # module -> sorted set of top-level names to import from it.
        by_module: dict[str, set[str]] = {}
        wellknown: set[str] = set()

        def consider(type_name: str) -> None:
            info = self._index.get(type_name)
            if info is None or info.file == file.name:
                return
            top = info.qualified.split(".")[0]
            claimant = f"{info.file}:{top}"
            if owner.setdefault(top, claimant) != claimant:
                msg = (
                    f"cannot generate {file.name}: two different types would both"
                    f" be imported as `{top}` ({owner[top]} and {claimant})"
                )
                raise ShortNameCollisionError(msg)
            if info.file.startswith("google/protobuf/"):
                # Structural well-known types ship inside the fastproto package.
                wellknown.add(top)
            else:
                by_module.setdefault(TypeIndex.module_of(info.file), set()).add(top)

        for type_name in self._referenced_type_names():
            consider(type_name)

        lines: list[str] = []
        if wellknown:
            joined = ", ".join(sorted(wellknown))
            lines.append(f"from fastproto.wellknown import {joined}")
        depth = file.name.count("/")
        for module, names in sorted(by_module.items()):
            joined = ", ".join(sorted(names))
            relative = "." * (1 + depth) + module
            lines += [
                "try:",
                f"    from {relative} import {joined}",
                "except ImportError:  # generated modules used outside a package",
                f"    from {module} import {joined}",
            ]
        return lines

    def _referenced_type_names(self) -> list[str]:
        """Full names of every message/enum referenced by this file's fields."""
        names: list[str] = []
        for msg in all_messages(self._file):
            for f in msg.field:
                entry = self._index.map_entry(f)
                target = (
                    next(x for x in entry.field if x.number == _MAP_VALUE_FIELD)
                    if entry is not None
                    else f
                )
                if is_named_type(target):
                    names.append(target.type_name)
        return names

    def _uses_scalar(self) -> bool:
        """Whether any generated annotation references a ``Scalar.*`` alias."""
        for msg in all_messages(self._file):
            for f in msg.field:
                if self._index.map_entry(f) is not None:
                    return True  # map keys are always scalar
                if f.type in SCALAR:
                    return True
        return False

    def _native_names(self) -> list[str]:
        """Sorted stdlib names (datetime/timedelta) referenced by this file."""
        names: set[str] = set()
        for msg in all_messages(self._file):
            for f in msg.field:
                entry = self._index.map_entry(f)
                target = (
                    next(x for x in entry.field if x.number == _MAP_VALUE_FIELD)
                    if entry is not None
                    else f
                )
                if target.type_name in NATIVE_WKT:
                    names.add(NATIVE_WKT[target.type_name])
        return sorted(names)

    def _file_blocks(self) -> list[str]:
        """Enum and message blocks of this proto file (no header)."""
        prefix = f".{self._file.package}" if self._file.package else ""
        blocks = [self._render_enum(enum) for enum in self._file.enum_type]
        blocks += [
            self._render_message(msg, f"{prefix}.{msg.name}")
            for msg in self._file.message_type
            if not msg.options.map_entry  # synthetic map entries aren't user-facing
        ]
        return blocks

    def _render_message(self, msg: DescriptorProto, full_name: str) -> str:
        """Render a message: its descriptor constants plus the class tree."""
        constants = self._collect_constants(msg, full_name)
        class_src = self._render_class(msg, full_name, 0)
        return "\n\n\n".join([*constants, class_src])

    def _collect_constants(self, msg: DescriptorProto, full_name: str) -> list[str]:
        """Descriptor constants for ``msg`` and nested messages, outermost first.

        The constants live at module level (even for nested classes) so a class
        body can reference its own constant, which is defined just above it.
        """
        const = self._descriptor_const_name(self._index.qualified_name(full_name))
        blocks = [
            "\n".join(
                [
                    f"{const} = bytes.fromhex(  # @generated",
                    f'    "{msg.SerializeToString().hex()}"',
                    ")",
                ],
            ),
        ]
        for nested in msg.nested_type:
            if not nested.options.map_entry:
                blocks += self._collect_constants(nested, f"{full_name}.{nested.name}")
        return blocks

    def _render_class(self, msg: DescriptorProto, full_name: str, indent: int) -> str:
        """Render one message class, recursing into nested enums and messages."""
        pad = "    " * indent
        inner = pad + "    "
        const = self._descriptor_const_name(self._index.qualified_name(full_name))
        header = [
            f"{pad}@message({const})",
            f"{pad}@dataclass(slots=True)",
            f"{pad}class {msg.name}(Message):",
        ]
        members = [self._render_enum(enum, indent + 1) for enum in msg.enum_type]
        members += [
            self._render_class(nested, f"{full_name}.{nested.name}", indent + 1)
            for nested in msg.nested_type
            if not nested.options.map_entry
        ]
        fields = [f"{inner}{self._render_field(f)}" for f in msg.field]
        body = [*members]
        if fields:
            body.append("\n".join(fields))
        if not body:
            body = [f"{inner}pass"]
        return "\n".join(header) + "\n" + "\n\n".join(body)

    def _render_field(self, field: FieldDescriptorProto) -> str:
        """Render one dataclass field line (without leading indentation).

        Annotations that reference a message or enum class are quoted: class-body
        annotations are evaluated eagerly (until PEP 649 lands in 3.14), so an
        unquoted forward or cyclic reference would raise ``NameError`` at import.
        """
        entry = self._index.map_entry(field)
        if entry is not None:
            key_field = next(f for f in entry.field if f.number == _MAP_KEY_FIELD)
            value_field = next(f for f in entry.field if f.number == _MAP_VALUE_FIELD)
            key = self._element_annotation(key_field)
            value = self._element_annotation(value_field)
            annotation = f"dict[{key}, {value}]"
            if is_named_type(value_field):  # map keys are always scalar
                annotation = f'"{annotation}"'
            return f"{field.name}: {annotation} = field(default_factory=dict)"

        if field.label == FieldDescriptorProto.LABEL_REPEATED:
            element = self._element_annotation(field)
            annotation = f"list[{element}]"
            if is_named_type(field):
                annotation = f'"{annotation}"'
            return f"{field.name}: {annotation} = field(default_factory=list)"

        return self._render_singular_field(field)

    def _render_singular_field(self, field: FieldDescriptorProto) -> str:
        """Render a non-repeated, non-map field line."""
        if field.type_name in NATIVE_WKT:
            # Native well-known type: plain stdlib object with presence.
            return f"{field.name}: {NATIVE_WKT[field.type_name]} | None = None"

        if field.type == FieldDescriptorProto.TYPE_MESSAGE:
            # Message fields always carry presence.
            return f'{field.name}: "{self._index.qualified(field)} | None" = None'

        if field.type == FieldDescriptorProto.TYPE_ENUM:
            return self._render_enum_field(field)

        annotation, default = SCALAR[field.type]
        if has_presence(field):
            return f"{field.name}: {annotation} | None = None"
        return f"{field.name}: {annotation} = {default}"

    def _render_enum_field(self, field: FieldDescriptorProto) -> str:
        """Render a singular enum field.

        A nested enum (``Outer.Color``) can't be named in the class body — the
        enclosing class isn't defined yet — so its annotation is quoted and its
        zero-value default is deferred to a factory that runs at instance
        creation. Top-level enums stay eager and unquoted.
        """
        qual = self._index.qualified(field)
        nested = "." in qual
        if has_presence(field):
            annotation = f'"{qual} | None"' if nested else f"{qual} | None"
            return f"{field.name}: {annotation} = None"
        if nested:
            return f'{field.name}: "{qual}" = field(default_factory=lambda: {qual}(0))'
        return f"{field.name}: {qual} = {qual}(0)"

    def _element_annotation(self, field: FieldDescriptorProto) -> str:
        """Return the annotation for a single scalar/enum/message element."""
        if field.type in SCALAR:
            return SCALAR[field.type][0]
        if field.type_name in NATIVE_WKT:
            return NATIVE_WKT[field.type_name]
        if field.type in (
            FieldDescriptorProto.TYPE_ENUM,
            FieldDescriptorProto.TYPE_MESSAGE,
        ):
            return self._index.qualified(field)
        return "object"  # group / unknown

    @staticmethod
    def _render_enum(enum: EnumDescriptorProto, indent: int = 0) -> str:
        """Render an enum as an ``IntEnum`` subclass, indented for nesting."""
        pad = "    " * indent
        body = [f"{pad}    {value.name} = {value.number}" for value in enum.value]
        header = f"{pad}class {enum.name}(IntEnum):"
        return "\n".join([header, *(body or [f"{pad}    pass"])])

    @staticmethod
    def _descriptor_const_name(qualified: str) -> str:
        """Descriptor constant name: ``Outer.Inner`` -> ``_OUTER_INNER_DESCRIPTOR``."""
        return f"_{qualified.replace('.', '_').upper()}_DESCRIPTOR"
